<?
/**
 * HANDLER VERIFICATION FOR BACKEND REQUEST
 * IF HANDLER IS ERROR, RETURN "BAD_HANDLER"
 */
if (HANDLER != HANDLER_SELF) {
    exit (Server\Response::FAILED('BAD_HANDLER' . HANDLER_SELF, true, HANDLER, NOW_SELF, 'error-msg'));
}
